/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const SignupLazyImport = createFileRoute('/signup')()
const SigninLazyImport = createFileRoute('/signin')()
const SettingsLazyImport = createFileRoute('/settings')()
const ServicesLazyImport = createFileRoute('/services')()
const ResetPasswordLazyImport = createFileRoute('/reset-password')()
const ProfileLazyImport = createFileRoute('/profile')()
const ManageBookingsLazyImport = createFileRoute('/manage-bookings')()
const ContactLazyImport = createFileRoute('/contact')()
const BookLazyImport = createFileRoute('/book')()
const AboutLazyImport = createFileRoute('/about')()

// Create/Update Routes

const SignupLazyRoute = SignupLazyImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/signup.lazy').then((d) => d.Route))

const SigninLazyRoute = SigninLazyImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/signin.lazy').then((d) => d.Route))

const SettingsLazyRoute = SettingsLazyImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/settings.lazy').then((d) => d.Route))

const ServicesLazyRoute = ServicesLazyImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/services.lazy').then((d) => d.Route))

const ResetPasswordLazyRoute = ResetPasswordLazyImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/reset-password.lazy').then((d) => d.Route),
)

const ProfileLazyRoute = ProfileLazyImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/profile.lazy').then((d) => d.Route))

const ManageBookingsLazyRoute = ManageBookingsLazyImport.update({
  id: '/manage-bookings',
  path: '/manage-bookings',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/manage-bookings.lazy').then((d) => d.Route),
)

const ContactLazyRoute = ContactLazyImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/contact.lazy').then((d) => d.Route))

const BookLazyRoute = BookLazyImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/book.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookLazyImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactLazyImport
      parentRoute: typeof rootRoute
    }
    '/manage-bookings': {
      id: '/manage-bookings'
      path: '/manage-bookings'
      fullPath: '/manage-bookings'
      preLoaderRoute: typeof ManageBookingsLazyImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileLazyImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordLazyImport
      parentRoute: typeof rootRoute
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesLazyImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsLazyImport
      parentRoute: typeof rootRoute
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninLazyImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutLazyRoute
  '/book': typeof BookLazyRoute
  '/contact': typeof ContactLazyRoute
  '/manage-bookings': typeof ManageBookingsLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/reset-password': typeof ResetPasswordLazyRoute
  '/services': typeof ServicesLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/signin': typeof SigninLazyRoute
  '/signup': typeof SignupLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutLazyRoute
  '/book': typeof BookLazyRoute
  '/contact': typeof ContactLazyRoute
  '/manage-bookings': typeof ManageBookingsLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/reset-password': typeof ResetPasswordLazyRoute
  '/services': typeof ServicesLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/signin': typeof SigninLazyRoute
  '/signup': typeof SignupLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutLazyRoute
  '/book': typeof BookLazyRoute
  '/contact': typeof ContactLazyRoute
  '/manage-bookings': typeof ManageBookingsLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/reset-password': typeof ResetPasswordLazyRoute
  '/services': typeof ServicesLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/signin': typeof SigninLazyRoute
  '/signup': typeof SignupLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/manage-bookings'
    | '/profile'
    | '/reset-password'
    | '/services'
    | '/settings'
    | '/signin'
    | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/manage-bookings'
    | '/profile'
    | '/reset-password'
    | '/services'
    | '/settings'
    | '/signin'
    | '/signup'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/manage-bookings'
    | '/profile'
    | '/reset-password'
    | '/services'
    | '/settings'
    | '/signin'
    | '/signup'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutLazyRoute: typeof AboutLazyRoute
  BookLazyRoute: typeof BookLazyRoute
  ContactLazyRoute: typeof ContactLazyRoute
  ManageBookingsLazyRoute: typeof ManageBookingsLazyRoute
  ProfileLazyRoute: typeof ProfileLazyRoute
  ResetPasswordLazyRoute: typeof ResetPasswordLazyRoute
  ServicesLazyRoute: typeof ServicesLazyRoute
  SettingsLazyRoute: typeof SettingsLazyRoute
  SigninLazyRoute: typeof SigninLazyRoute
  SignupLazyRoute: typeof SignupLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutLazyRoute: AboutLazyRoute,
  BookLazyRoute: BookLazyRoute,
  ContactLazyRoute: ContactLazyRoute,
  ManageBookingsLazyRoute: ManageBookingsLazyRoute,
  ProfileLazyRoute: ProfileLazyRoute,
  ResetPasswordLazyRoute: ResetPasswordLazyRoute,
  ServicesLazyRoute: ServicesLazyRoute,
  SettingsLazyRoute: SettingsLazyRoute,
  SigninLazyRoute: SigninLazyRoute,
  SignupLazyRoute: SignupLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/about",
        "/book",
        "/contact",
        "/manage-bookings",
        "/profile",
        "/reset-password",
        "/services",
        "/settings",
        "/signin",
        "/signup"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/about": {
      "filePath": "about.lazy.jsx"
    },
    "/book": {
      "filePath": "book.lazy.jsx"
    },
    "/contact": {
      "filePath": "contact.lazy.jsx"
    },
    "/manage-bookings": {
      "filePath": "manage-bookings.lazy.jsx"
    },
    "/profile": {
      "filePath": "profile.lazy.jsx"
    },
    "/reset-password": {
      "filePath": "reset-password.lazy.jsx"
    },
    "/services": {
      "filePath": "services.lazy.jsx"
    },
    "/settings": {
      "filePath": "settings.lazy.jsx"
    },
    "/signin": {
      "filePath": "signin.lazy.jsx"
    },
    "/signup": {
      "filePath": "signup.lazy.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
